/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#aad4f2",
        "on-secondary-container": "#b2c0d9",
        "inverse-on-surface": "#4a5569",
        "surface-container-lowest": "#000000",
        "on-primary": "#1b4747",
        "on-error": "#490006",
        "inverse-surface": "#f9f9ff",
        "inverse-primary": "#3c6666",
        "tertiary-fixed": "#aad4f2",
        "surface-dim": "#040e1f",
        "on-tertiary-fixed": "#01364e",
        "secondary-fixed-dim": "#c7d5ee",
        "secondary-dim": "#abbad2",
        "surface-container": "#041a35",
        "on-tertiary": "#28536b",
        "on-secondary": "#334155",
        "on-tertiary-fixed-variant": "#28536c",
        "primary-dim": "#96c1c1",
        "surface-container-high": "#08203d",
        "on-primary-fixed": "#1a4646",
        "on-error-container": "#ff9993",
        "error": "#fa746f",
        "surface-tint": "#a3cfce",
        "on-secondary-fixed": "#324054",
        "primary-container": "#2f5959",
        "on-secondary-fixed-variant": "#4e5c71",
        "surface": "#040e1f",
        "on-primary-fixed-variant": "#396263",
        "on-tertiary-container": "#1e4a62",
        "secondary-container": "#2e3c50",
        "on-background": "#dae6ff",
        "outline": "#5e769e",
        "primary": "#a3cfce",
        "tertiary-dim": "#9dc6e3",
        "on-surface-variant": "#94acd7",
        "secondary-fixed": "#d5e3fd",
        "secondary": "#b9c7e0",
        "tertiary": "#bae2ff",
        "error-container": "#871f21",
        "primary-fixed": "#bfebea",
        "outline-variant": "#30486e",
        "surface-container-low": "#03132a",
        "on-primary-container": "#bfeceb",
        "tertiary-fixed-dim": "#9dc6e3",
        "surface-bright": "#112c50",
        "error-dim": "#c54d4a",
        "background": "#040e1f",
        "primary-fixed-dim": "#b1dddc",
        "on-surface": "#dae6ff",
        "surface-container-highest": "#082649",
        "surface-variant": "#082649",
        // Retain brand for legacy pages safely until fully refactored
        "brand": "rgb(var(--brand) / <alpha-value>)", 
        "brand-hover": "rgb(var(--brand-hover) / <alpha-value>)",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        sans: ["Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      backgroundImage: {
        'brand-glow': 'linear-gradient(145deg, #a3cfce, #2f5959)',
      }
    },
  },
  plugins: [],
};
